// <auto-generated />
using System;
using Backend.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Persistence
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Backend.Persistence.Priority", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Low"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("Backend.Persistence.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FkPriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FkTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FkPriorityId");

                    b.HasIndex("FkTypeId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "job a",
                            DueDate = new DateTime(2023, 11, 24, 16, 30, 11, 859, DateTimeKind.Local).AddTicks(6337),
                            FkPriorityId = 1,
                            FkTypeId = 1,
                            Name = "Small",
                            StartDate = new DateTime(2023, 11, 24, 16, 30, 11, 859, DateTimeKind.Local).AddTicks(6324)
                        });
                });

            modelBuilder.Entity("Backend.Persistence.Type", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Work"
                        });
                });

            modelBuilder.Entity("Backend.Persistence.Task", b =>
                {
                    b.HasOne("Backend.Persistence.Priority", "FkPriority")
                        .WithMany("Tasks")
                        .HasForeignKey("FkPriorityId");

                    b.HasOne("Backend.Persistence.Type", "FkType")
                        .WithMany("Tasks")
                        .HasForeignKey("FkTypeId");

                    b.Navigation("FkPriority");

                    b.Navigation("FkType");
                });

            modelBuilder.Entity("Backend.Persistence.Priority", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Backend.Persistence.Type", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
